# ç«™ç‚¹Icon
favicon: /favicon.ico

# è€å©†åå•
girls:
  enable: true

# å¤´åƒ
avatar:
  enable: true
  url: /images/avatar.jpg
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: false
    emoji: ğŸ˜«
    message: ä¸æƒ³ä¸Šç­

# èƒŒæ™¯
bg_image:
  enable: true
  url: https://static.7os.top/Image/Blog/BackImg/1574784866873.png
  dark: https://static.7os.top/Image/Blog/BackImg/wallhaven-1k6ljv.jpg
  # blur: 30px 
  opacity: 0.6

# ä»£ç å—å¤åˆ¶æŒ‰é’®
codeblock:
  copy_btn: true

# æ ‡è¯­åŠ¨ç”»
banner:
  enable: true
  title: å·å¾—æµ®ç”ŸåŠæ—¥é—²
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

# å…¬å‘Š
# notice:
#   enable: true
#   content: Thanks for playing my game.

# ç¤¾äº¤å›¾æ ‡
social:
  - name: Github
    link: https://github.com/Sakura70s
    icon: ri:github-line
    color: '#181717'
  - name: E-Mail
    link: mailto:Sakura70s@outlook.com
    icon: ri:mail-line
    color: '#8E71C1'
  - name: Bilibili
    link: https://space.bilibili.com/54346474
    icon: ri:bilibili-line
    color: '#FF8EB3'

# ä¾§è¾¹æ å±•ç¤ºåˆ†ç±»
pages:
  - name: æˆ‘çš„å·¦è¾¹ç¿…è†€
    url: /links/
    icon: ri:genderless-line
    color: dodgerblue
  - name: æˆ‘çš„å³è¾¹ç¿…è†€
    url: /girls/
    icon: ri:women-line
    color: hotpink