# å¤´åƒ
avatar:
  enable: true
  url: /images/avatar.jpg
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: false
    emoji: ğŸ˜«
    message: ä¸æƒ³ä¸Šç­

# æ ‡è¯­åŠ¨ç”»
banner:
  enable: true
  title: å·å¾—æµ®ç”ŸåŠæ—¥é—²
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line
